# Generated by Django 5.2.17 on 2026-09-09 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('automatic', models.BooleanField(default=False)),
                ('strength', models.CharField(default='light', max_length=8)),
                ('automatic_since', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_digest', models.CharField(max_length=64)),
                ('source_path', models.CharField(max_length=512)),
                ('strength', models.CharField(max_length=8)),
                ('algorithm', models.CharField(max_length=80)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('adoption_serial', models.PositiveIntegerField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=256)),
                ('output_path', models.CharField(blank=True, default='', max_length=512)),
                ('output_digest', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('identity', models.CharField(max_length=64)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_digest', models.CharField(max_length=64)),
                ('source_path', models.CharField(max_length=512)),
                ('adopted', models.CharField(default='original', max_length=12)),
                ('adoption_serial', models.PositiveIntegerField(default=0)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='postprocessing.imagejob')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_versions', to='history.historyrecord')),
            ],
        ),
        migrations.AddField(
            model_name='imagejob',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='postprocessing.imagepage'),
        ),
        migrations.AddConstraint(
            model_name='imagepage',
            constraint=models.UniqueConstraint(fields=('record', 'index'), name='processing_record_page'),
        ),
        migrations.AddIndex(
            model_name='imagejob',
            index=models.Index(fields=['status', 'created_at'], name='processing_queue'),
        ),
        migrations.AddConstraint(
            model_name='imagejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'processing'])), fields=('page',), name='processing_one_active_page'),
        ),
    ]
