# Generated by Django 5.2.17 on 2026-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='published_revision',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
