# Generated by Django 5.2.17 on 2026-09-11 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('preferences', models.JSONField(default=dict)),
                ('references', models.JSONField(default=list)),
                ('provider', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='prepared', max_length=20)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
