# Generated by Django 5.2.17 on 2026-08-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('outline', models.JSONField(blank=True, default=dict)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='accounts.user')),
            ],
            options={
                'db_table': 'history_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
