# Generated by Django 5.2.17 on 2026-09-26 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_image_path', models.CharField(blank=True, default='', max_length=512)),
                ('source_image_digest', models.CharField(blank=True, default='', max_length=64)),
                ('content', models.JSONField(default=dict)),
                ('layout', models.JSONField(default=dict)),
                ('visual_style', models.JSONField(default=dict)),
                ('rewritten_content', models.TextField(blank=True, default='')),
                ('user_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=120)),
                ('image_path', models.CharField(blank=True, default='', max_length=512)),
                ('content', models.JSONField(default=dict)),
                ('rewritten_content', models.TextField(blank=True, default='')),
                ('user_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_assets', to='reference_assets.imageanalysis')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_assets', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
