# Generated by Django 5.2.17 on 2026-09-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptEntry',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=16)),
                ('category', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('legacy_value', models.CharField(default='', max_length=100)),
                ('builtin', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('visibility', models.CharField(default='private', max_length=16)),
                ('allowed_users', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('default_snapshot', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'ordering': ['module', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='prompts.promptentry')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'number'), name='prompt_version_number')],
            },
        ),
    ]
